class_name CardDef
extends RefCounted

## Canonical card definition — the immutable identity of a card. Master prompt 9.
##
## Loaded from Data/cards/cards.json, which is generated by Tools/build_card_db.py
## from text verified against the official Konami card database.
##
## A CardDef is shared by every copy of that card in a duel. Per-copy mutable state
## lives on CardInstance. Modified stats are NEVER written back here.

var name: String = ""
var official_name: String = ""
var passcode: String = ""
var konami_cid: String = ""
var source_url: String = ""
var text: String = ""

var category: Enums.Category = Enums.Category.MONSTER

# --- Monster fields ---
var race: String = ""
var attribute: String = ""
var level: int = 0
var base_atk: int = 0
var base_def: int = 0
var is_normal_monster: bool = false
var is_effect_monster: bool = false
var is_tuner: bool = false
var is_flip_monster: bool = false
var monster_subtypes: PackedStringArray = PackedStringArray()

# --- Spell/Trap fields ---
var st_kind: Enums.STKind = Enums.STKind.NONE

## Card-level Spell Speed used when activating the card itself.
## Individual monster effects carry their own Spell Speed on their EffectDef.
var spell_speed: int = Enums.SpellSpeed.SS1

## Effect definitions for this card, filled in by the card registry.
## An empty array on an Effect Monster / Spell / Trap is a load-time error —
## see Scripts/rules/DataValidation.gd (master prompt 67: no silent fallbacks).
var effects: Array = []


static func from_dict(d: Dictionary) -> CardDef:
	var c := CardDef.new()
	c.name = d.get("name", "")
	c.official_name = d.get("official_name", c.name)
	c.passcode = str(d.get("passcode", ""))
	c.konami_cid = str(d.get("konami_cid", ""))
	c.source_url = d.get("source_url", "")
	c.text = d.get("text", "")

	match d.get("category", "Monster"):
		"Monster":
			c.category = Enums.Category.MONSTER
		"Spell":
			c.category = Enums.Category.SPELL
		"Trap":
			c.category = Enums.Category.TRAP

	if c.category == Enums.Category.MONSTER:
		c.race = d.get("race", "")
		c.attribute = d.get("attribute", "")
		c.level = int(d.get("level", 0))
		c.base_atk = int(d.get("atk", 0))
		c.base_def = int(d.get("def", 0))
		c.is_normal_monster = bool(d.get("is_normal", false))
		c.is_effect_monster = bool(d.get("is_effect", false))
		c.is_tuner = bool(d.get("is_tuner", false))
		c.is_flip_monster = bool(d.get("is_flip", false))
		var subs := PackedStringArray()
		for s in d.get("monster_subtypes", []):
			subs.append(str(s))
		c.monster_subtypes = subs
		c.spell_speed = Enums.SpellSpeed.SS1
	else:
		c.st_kind = Enums.st_kind_from_icon(d.get("icon", ""))
		c.spell_speed = Enums.spell_speed_for_st(c.st_kind)

	return c


func is_monster() -> bool:
	return category == Enums.Category.MONSTER


func is_spell() -> bool:
	return category == Enums.Category.SPELL


func is_trap() -> bool:
	return category == Enums.Category.TRAP


## Level 5-6 need 1 Tribute, Level 7+ need 2. [S1 p.24-25]
## Card effects may modify this (e.g. Kaiser Sea Horse); that adjustment happens
## in SummonRules, not here.
func base_tributes_required() -> int:
	if not is_monster():
		return 0
	if level >= 7:
		return 2
	if level >= 5:
		return 1
	return 0


## True when the card has no effects at all and is purely a vanilla body.
func is_vanilla() -> bool:
	return is_monster() and is_normal_monster and effects.is_empty()


func type_line() -> String:
	if is_monster():
		var parts := [race]
		for s in monster_subtypes:
			parts.append(s)
		return "/".join(parts)
	return _st_kind_label()


func _st_kind_label() -> String:
	match st_kind:
		Enums.STKind.NORMAL_SPELL: return "Normal Spell"
		Enums.STKind.QUICK_PLAY_SPELL: return "Quick-Play Spell"
		Enums.STKind.CONTINUOUS_SPELL: return "Continuous Spell"
		Enums.STKind.EQUIP_SPELL: return "Equip Spell"
		Enums.STKind.FIELD_SPELL: return "Field Spell"
		Enums.STKind.RITUAL_SPELL: return "Ritual Spell"
		Enums.STKind.NORMAL_TRAP: return "Normal Trap"
		Enums.STKind.CONTINUOUS_TRAP: return "Continuous Trap"
		Enums.STKind.COUNTER_TRAP: return "Counter Trap"
		_: return "Unknown"


func _to_string() -> String:
	return "CardDef(%s)" % name
